name: Ejercicio_1
on:
  workflow_dispatch:
env:
  MESSAGE: "Hello World"
jobs:
  say_hello:
    name: "Let's greet the user!"
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ env.MESSAGE }}"
  
  check_message:
    name: "Let's check the message!"
    runs-on: ubuntu-latest
    steps:
      - run: echo "The message is ${{ env.MESSAGE }}"

